services:
  - type: web
    name: english-booking
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        sync: false
        value: "10000"